name: Python Linting and Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Use your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pylint
      run: |
        echo "Running pylint..."
        pylint src/ tests/ || true  # Allow the pipeline to continue even if pylint fails


    - name: Run flake8
      run: |
        echo "Running flake8..."
        flake8 src/ tests/

    # Optional: Run tests with pytest
    - name: Run tests
      run: |
        echo "Running tests..."
        pytest --maxfail=1 --disable-warnings
